/**
 * Eason Chan song library — enriched data.
 * Built from music_data/Eason_music_all.xlsx + manual mood annotations.
 *
 * Data source: songs_enriched.json (generated by scripts/build_enriched.py)
 */

import songsData from "@/data/songs_enriched.json";

export interface SongPrescriptionTemplates {
  songReason: string[];
  dosage: string[];
  listeningScene: string[];
  doctorAdvice: string[];
  dailyTask: string[];
  avoid: string[];
  followUp: string[];
}

export interface SongData {
  id: string;
  title: string;
  displayTitle: string;
  album: string;
  albumType: "studio" | "compilation" | "live" | "single" | "unknown" | "radio_drama";
  albumCover: string | null;
  primaryMood: string;
  moods: string[];
  keywords: string[];
  popularityWeight: number;
  themeColor: string;
  icon: string;
  prescriptionTemplates: SongPrescriptionTemplates;
}

/** Full curated song list for the recommendation engine */
export const songs: SongData[] = songsData as SongData[];

/** Get default cover path or fallback */
export function getCoverUrl(cover: string | null): string {
  return cover || "/assets/default_cover.svg";
}

/** Total songs in curated pool */
export const totalSongs = songs.length;

/** Quick lookup by ID */
export function getSongById(id: string): SongData | undefined {
  return songs.find((s) => s.id === id);
}
